### PR TITLE
use membrane peptide dataset for on-the-fly transformations

### LINKED ISSUE #13: data files for on-the-fly transformations missing
The notebook [transformations/on-the-fly-transformations.ipynb](https://github.com/MDAnalysis/binder-notebook/blob/master/notebooks/transformations/on-the-fly-transformations.ipynb) (open in [nbviewer](https://nbviewer.jupyter.org/github/MDAnalysis/binder-notebook/blob/master/notebooks/transformations/on-the-fly-transformations.ipynb)) (which was added in PR #10 ) uses 
```python
u = mda.Universe('pept_in_memb.tpr', 'pept_in_memb.xtc')
```
These files `pept_in_memb.tpr', 'pept_in_memb.xtc'` are not installed with binder so the notebook will not run on binder. All notebooks should be fully self-contained.

Possible solutions:
- add these files in MDAnalysisTests or replace with files in MDAnalysisTests
- add these files to https://github.com/MDAnalysis/MDAnalysisData and install MDAnalysisData as part of our binder set up

### PR DESCRIPTION
**Pull request by orbeckst**
fixes #13 

- add MDAnalysisData to environment
- use membrane protein dataset

### CODE REVIEW

**Comment by orbeckst** [comment]
This will need a release of MDAnalysis 0.20.0 to _actually_ work but otherwise I think it's ok.

**Comment by orbeckst** [comment]
@davidercruz if you could try it out locally in a branch of your code that has the transformations?

To get MDAnalysisData install with pip (conda not up yet I think)
```
pip install MDAnalysisData
```

**Comment by orbeckst** [comment]
PR https://github.com/conda-forge/mdanalysisdata-feedstock/pull/5 just got merged so the conda package should be up soon, too, so you can also install with
```
conda install -c conda-forge MDAnalysisData
```

**Comment by davidercruz** [comment]
Hi @orbeckst. I just tried it and it works as expected. It's just a bit slower on my computer due to the higher number of frames, but other than that it is fine.

**Comment by orbeckst** [comment]
Thanks!

**Pull request merged**
