### PR TITLE
Hole notebooks

### PR DESCRIPTION
**Pull request by orbeckst**
Started on the original gists. 

However, for these notebooks to work we need a conda package for hole https://github.com/MDAnalysis/mdanalysis/issues/1429 so that it can be installed in Binder.

### CODE REVIEW

**Comment by orbeckst** [comment]
The hole-orderparameter.ipynb notebook refuses to run as originally. 
```python
ref = mda.Universe(PDB_HOLE)    # reference structure
u = mda.Universe(MULTIPDB_HOLE) # trajectory
R = RMSD(u, reference=ref, select="protein", weights="mass")
R.run()
```
fails with (cryptic!)
```
MDAnalysis.analysis.rmsd: INFO     RMS calculation for 260 atoms.
MDAnalysis.analysis.rmsd: ERROR    Atoms: reference | mobile
MDAnalysis.analysis.rmsd: ERROR    Inconsistent selections, masses differ by more than0.100000; mis-matching atomsare shown above.
```

**Comment by kain88-de** [comment]
I can add a script to install while I think. I can check during the week.

**Comment by kain88-de** [comment]
I mean install a script to install hole.

**Comment by kain88-de** [comment]
https://mybinder.org/v2/gh/MDAnalysis/binder-notebook/hole-notebooks

@orbeckst I added an install script. Maybe it works. The link above is the binder for the new branch to test.

**Comment by kain88-de** [comment]
@orbeckst I have no idea what the error message is btw. If hole is missing we should have a better error message.

**Comment by kain88-de** [comment]
The `hole-basics` notebook works. The `hole-orderparameter` notebook fails due to changes in the library. It would be beneficial to test the notebooks with releases.

**Comment by orbeckst** [comment]
Thanks for adding the installation script. It worked for me: I was able to run all of https://hub.mybinder.org/user/mdanalysis-binder-notebook-ymw4ep1z/notebooks/analysis/hole-basics.ipynb without issues.

I am not sure what error message you're referring to.

The second notebook https://hub.mybinder.org/user/mdanalysis-binder-notebook-ymw4ep1z/notebooks/analysis/hole-orderparameter.ipynb is failing but not because of hole.

**Comment by kain88-de** [comment]
The cryptic error you had in https://github.com/MDAnalysis/binder-notebook/pull/1#issuecomment-364784645

**Comment by orbeckst** [comment]
Yes – that's not hole but other stuff. Not sure what we changed to make it fail now. Need to investigate.

(And it fails locally for me, too.)

**Comment by orbeckst** [comment]
I can split the PR and we only put up the working notebook for right now. Should we do that?

**Comment by kain88-de** [comment]
Yeah that would be good. I think we also need to clean the install script. The artifacts that the hole installation leaves should be cleaned as they can be confusing.

**Comment by orbeckst** [comment]
Yes & yes.

**Comment by orbeckst** [comment]
PR https://github.com/MDAnalysis/mdanalysis/pull/1783 will fix the problem with the second notebook and it will work with MDAnalysis 0.17.1.

**Comment by orbeckst** [comment]
I decided to add both notebooks. The second one has a comment that it needs MDA 0.17.1 (but it's not very conspicuous). I hope we'll get PR MDAnalysis/mdanalysis#1783  merged soon and 0.17.1 released, then I don't have to worry about. 

I can open an issue saying that the notebook is not full working once this PR is merged. At least in this way there's an official acknowledgment and we can easily close the issue once 0.17.1 is out.

I remove the hole tar file. I am not sure how to test this – can I run binder on a branch?

**Comment by kain88-de** [comment]
> can I run binder on a branch?

See: https://github.com/MDAnalysis/binder-notebook/pull/1#issuecomment-366079295

**Comment by orbeckst** [comment]
D'oh. Thanks.

**Comment by orbeckst** [comment]
The downloaded hole tar file is gone. The new `~/hole2` directory might be a bit confusing but we might have to think a bit more how to organize the file system anyway. Perhaps just put all notebooks into a directory "notebooks" to make clear where to look?

I am inclined to merge it now, even though the hole-orderparameter notebook will only start working properly with MDA 0.17.1. 

Any other opinions?

**Pull request merged**
